[openai]
OPENAI_API_KEY = "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"

[email]
SENDER_EMAIL = "your_email@gmail.com"
SENDER_PASSWORD = "your_google_app_password" # Use a Google App Password, not your regular password
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587